<section id="container">
                
    <h1 class="hidden">Check our product out!</h1>
    <div id="teaserPic">
        <figure>
            <img src='<?= $this->translate('home.teaserPicUrl'); ?>' alt='<?= $this->translate('home.teaserPicAlt'); ?>' />
        </figure>
    </div>

    <div id="divTeaserTxt">
        <h1><?= $this->translate('home.teaserTitle'); ?></h1>
        <h2><?= $this->translate('home.teaserSubtitle'); ?></h2>
        <p>
            <?= $this->translate('home.teaserTxt'); ?> 
        </p>
    </div>


</section>

<section id="mainContent">

    <h1 class="hidden">This is the main part of the website</h1>
    <article id="main">

        <h1><?= $this->translate('home.title'); ?></h1>
        <p><?= $this->translate('home.txt'); ?></p>
    </article>

</section>