<section id="container">
                
    <h1 class="hidden">Check our product out!</h1>
    <div id="teaserPic">
        <figure>
            <img src='<?= $this->translate('services.teaserPicUrl'); ?>' alt='<?= $this->translate('services.teaserPicAlt'); ?>' />
        </figure>
    </div>

    <div id="divTeaserTxt">
        <h1><?= $this->translate('services.teaserTitle'); ?></h1>
        <h2><?= $this->translate('services.teaserSubtitle'); ?></h2>
        <p>
            <?= $this->translate('services.teaserTxt'); ?> 
        </p>
    </div>


</section>

<section id="mainContent">

    <h1 class="hidden">This is the main part of the website</h1>
    <article id="main">

        <h1><?= $this->translate('services.title'); ?></h1>
        <p><?= $this->translate('services.txt'); ?></p>
    </article>

</section>