<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Eindwerk</title>
        <link rel="stylesheet" type="text/css" media="screen" href="css/screen.css" />
    </head>
    <body>
        
        <div id="wrapper">
            
            <header>
                <h1 class="hidden"><?= $this->translate('text.header');?></h1>
                <div id="logo">
                    <p><a href="#"><?= $this->translate('text.header');?></a></p>
                </div>
                <nav>
                    <h1 class="hidden">Site navigation</h1>
                    <?= $this->navigation()->menu(); ?>
                 </nav>
            </header>
            
            <?php echo $this->layout()->content; ?>
            
            <footer>
                <h1 class="hidden">&copy; Joeri Lambert</h1>
                <p><?= $this->translate('text.footer'); ?></p>
                
            </footer>
            
        </div>
        
    </body>
</html>